In [1]:
#라이브러리 및 데이터 로드
import pandas as pd

x_train=pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/shipping/X_train.csv')
y_train=pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/shipping/y_train.csv')
x_test=pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/shipping/X_test.csv')

x_train.head()
y_train.head()

     ID  Reached.on.Time_Y.N
0  6045                    0
1    44                    1
2  7940                    1
3  1596                    1
4  4395                    1

In [5]:
# 3.EDA
print(x_train.info())
print(x_train.nunique())
print(x_train.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6598 entries, 0 to 6597
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   6598 non-null   int64
 1   Warehouse_block      6598 non-null   object
 2   Mode_of_Shipment     6598 non-null   object
 3   Customer_care_calls  6598 non-null   object
 4   Customer_rating      6598 non-null   int64
 5   Cost_of_the_Product  6598 non-null   int64
 6   Prior_purchases      6598 non-null   int64
 7   Product_importance   6598 non-null   object
 8   Gender               6598 non-null   object
 9   Discount_offered     6598 non-null   int64
 10  Weight_in_gms        6598 non-null   int64
dtypes: int64(6), object(5)
memory usage: 567.1+ KB
None
ID                     6598
Warehouse_block           5
Mode_of_Shipment          3
Customer_care_calls       6
Customer_rating           5
Cost_of_the_Product     215
Prior_purchases           8
Product_importance        3
Gender                    2
Discount_offered         65
Weight_in_gms          3365
dtype: int64
ID                     0
Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
dtype: int64

In [6]:
# 4. 결측치 처리
drop_col=['ID']
x_train_drop=x_train.drop(columns=drop_col)
x_test_drop=x_test.drop(columns=drop_col)

In [15]:
# 5. 머신러닝 구현
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [17]:
x_train_dummies=pd.get_dummies(x_train_drop)
y=y_train['Reached.on.Time_Y.N']

In [18]:
x_test_dummies=pd.get_dummies(x_test_drop)
x_test_dummies=x_test_dummies[x_train_dummies.columns]

In [19]:
X_train,X_validation,Y_train,Y_validation=train_test_split(x_train_dummies,y,test_size=0.33, random_state=42)
rf=RandomForestClassifier(random_state=23)
rf.fit(X_train,Y_train)

RandomForestClassifier(random_state=23)

In [20]:
import sklearn.metrics
dir(sklearn.metrics)

['ConfusionMatrixDisplay',
 'DetCurveDisplay',
 'DistanceMetric',
 'PrecisionRecallDisplay',
 'PredictionErrorDisplay',
 'RocCurveDisplay',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_base',
 '_classification',
 '_dist_metrics',
 '_pairwise_distances_reduction',
 '_pairwise_fast',
 '_plot',
 '_ranking',
 '_regression',
 '_scorer',
 'accuracy_score',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'auc',
 'average_precision_score',
 'balanced_accuracy_score',
 'brier_score_loss',
 'calinski_harabasz_score',
 'check_scoring',
 'class_likelihood_ratios',
 'classification_report',
 'cluster',
 'cohen_kappa_score',
 'completeness_score',
 'confusion_matrix',
 'consensus_score',
 'coverage_error',
 'd2_absolute_error_score',
 'd2_log_loss_score',
 'd2_pinball_score',
 'd2_tweedie_score',
 'davies_bouldin_score',
 'dcg_score',
 'det_curve',
 'euclidean_distances',
 'explained_variance_score',
 'f1_score',
 'fbeta_score',
 'fowlkes_mallows_score',
 'get_scorer',
 'get_scorer_names',
 'hamming_loss',
 'hinge_loss',
 'homogeneity_completeness_v_measure',
 'homogeneity_score',
 'jaccard_score',
 'label_ranking_average_precision_score',
 'label_ranking_loss',
 'log_loss',
 'make_scorer',
 'matthews_corrcoef',
 'max_error',
 'mean_absolute_error',
 'mean_absolute_percentage_error',
 'mean_gamma_deviance',
 'mean_pinball_loss',
 'mean_poisson_deviance',
 'mean_squared_error',
 'mean_squared_log_error',
 'mean_tweedie_deviance',
 'median_absolute_error',
 'multilabel_confusion_matrix',
 'mutual_info_score',
 'nan_euclidean_distances',
 'ndcg_score',
 'normalized_mutual_info_score',
 'pair_confusion_matrix',
 'pairwise',
 'pairwise_distances',
 'pairwise_distances_argmin',
 'pairwise_distances_argmin_min',
 'pairwise_distances_chunked',
 'pairwise_kernels',
 'precision_recall_curve',
 'precision_recall_fscore_support',
 'precision_score',
 'r2_score',
 'rand_score',
 'recall_score',
 'roc_auc_score',
 'roc_curve',
 'root_mean_squared_error',
 'root_mean_squared_log_error',
 'silhouette_samples',
 'silhouette_score',
 'top_k_accuracy_score',
 'v_measure_score',
 'zero_one_loss']

In [21]:
from sklearn.metrics import accuracy_score, f1_score, recall_score, roc_auc_score, precision_score

In [22]:
predict_train_label=rf.predict(X_train)
predict_train_proba=rf.predict_proba(X_train)[:,1]

In [28]:
predict_validation_label=rf.predict(X_validation)
predict_validation_prob=rf.predict_proba(X_validation)[:,1]

In [29]:
print('train accuracy: ', accuracy_score(Y_train,predict_train_label))
print('validation accuracy: ', accuracy_score(Y_validation,predict_validation_label))
print('\n')
print('train f1_score :', f1_score(Y_train,predict_train_label))
print('validation f1_score :', f1_score(Y_validation,predict_validation_label))
print('\n')
print('train recall_score :', recall_score(Y_train,predict_train_label))
print('validation recall_score :', recall_score(Y_validation,predict_validation_label))
print('\n')
print('train precision_score :', precision_score(Y_train,predict_train_label))
print('validation precision_score :', precision_score(Y_validation,predict_validation_label))
print('\n')
print('train auc :', roc_auc_score(Y_train,predict_train_proba))
print('validation auc :', roc_auc_score(Y_validation,predict_validation_prob))

train accuracy:  1.0
validation accuracy:  0.6395775941230487


train f1_score : 1.0
validation f1_score : 0.6744089589382


train recall_score : 1.0
validation recall_score : 0.630721489526765


train precision_score : 1.0
validation precision_score : 0.7245989304812834


train auc : 1.0
validation auc : 0.7261997118475008

In [32]:
predict_test_label=rf.predict(x_test_dummies)
predict_test_proba=rf.predict_proba(x_test_dummies)[:,1]

In [33]:
pd.DataFrame({'ID': x_test.ID, 'Reached.on.Time_Y.N': predict_test_label}).to_csv('003000000.csv', index=False)

In [34]:
pd.DataFrame({'ID': x_test.ID, 'Reached.on.Time_Y.N': predict_test_proba}).to_csv('003000000.csv', index=False)

# 비행탑승 경험 만족도 데이터

In [1]:
import pandas as pd
x_train=pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_train.csv")
y_train=pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/y_train.csv")
x_test=pd.read_csv("https://raw.githubusercontent.com/Datamanim/datarepo/main/airline/x_test.csv")

display(x_train.head())
display(y_train.head())

,ID,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id
0,0,Female,Loyal Customer,54,Personal Travel,Eco,1068,3,4,3,...,5,5,3,5,3,5,3,47,22.0,NaN
1,2,Male,Loyal Customer,20,Personal Travel,Eco,1546,4,4,4,...,4,3,3,4,4,4,4,5,2.0,NaN
2,3,Male,Loyal Customer,59,Business travel,Business,2962,0,4,0,...,1,1,1,1,5,1,4,54,46.0,NaN
3,4,Male,Loyal Customer,35,Business travel,Eco Plus,106,5,4,4,...,5,2,1,5,4,4,5,130,121.0,NaN
4,5,Female,Loyal Customer,9,Business travel,Business,2917,3,3,3,...,4,4,4,5,4,3,4,0,0.0,NaN

   ID             satisfaction
0   0  neutral or dissatisfied
1   2  neutral or dissatisfied
2   3                satisfied
3   4                satisfied
4   5                satisfied

## 3. EDA

In [3]:
x_train.shape
display(x_train.info())
display(x_train.describe())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 83123 entries, 0 to 83122
Data columns (total 24 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   ID                                 83123 non-null  int64
 1   Gender                             83123 non-null  object
 2   Customer Type                      83123 non-null  object
 3   Age                                83123 non-null  int64
 4   Type of Travel                     83123 non-null  object
 5   Class                              83123 non-null  object
 6   Flight Distance                    83123 non-null  int64
 7   Inflight wifi service              83123 non-null  int64
 8   Departure/Arrival time convenient  83123 non-null  int64
 9   Ease of Online booking             83123 non-null  int64
 10  Gate location                      83123 non-null  int64
 11  Food and drink                     83123 non-null  int64
 12  Online boarding                    83123 non-null  int64
 13  Seat comfort                       83123 non-null  int64
 14  Inflight entertainment             83123 non-null  int64
 15  On-board service                   83123 non-null  int64
 16  Leg room service                   83123 non-null  int64
 17  Baggage handling                   83123 non-null  int64
 18  Checkin service                    83123 non-null  int64
 19  Inflight service                   83123 non-null  int64
 20  Cleanliness                        83123 non-null  int64
 21  Departure Delay in Minutes         83123 non-null  int64
 22  Arrival Delay in Minutes           82867 non-null  float64
 23  id                                 0 non-null      float64
dtypes: float64(2), int64(18), object(4)
memory usage: 15.2+ MB

None

,ID,Age,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,Food and drink,Online boarding,Seat comfort,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,id
count,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.000000,83123.00000,83123.000000,82867.000000,0.0
mean,52003.849657,39.360249,1191.164455,2.729545,3.060296,2.757612,2.978405,3.204721,3.252060,3.440588,3.359660,3.382060,3.351299,3.632641,3.302516,3.642686,3.28690,14.777763,15.132477,NaN
std,29972.640033,15.102492,997.171944,1.327213,1.523947,1.398630,1.277390,1.330112,1.349006,1.319980,1.332698,1.287719,1.315613,1.180139,1.262015,1.175697,1.31147,37.904165,38.396170,NaN
min,0.000000,7.000000,31.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.00000,0.000000,0.000000,NaN
25%,26120.500000,27.000000,414.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,3.000000,3.000000,3.000000,2.00000,0.000000,0.000000,NaN
50%,52004.000000,40.000000,846.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,4.000000,4.000000,4.000000,4.000000,4.000000,3.000000,4.000000,3.00000,0.000000,0.000000,NaN
75%,77935.500000,51.000000,1744.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,5.000000,4.000000,4.000000,4.000000,5.000000,4.000000,5.000000,4.00000,12.000000,13.000000,NaN
max,103903.000000,85.000000,4983.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.00000,1592.000000,1584.000000,NaN

## 4. 데이터 전처리

In [5]:
x_train.isnull().sum()

ID                                       0
Gender                                   0
Customer Type                            0
Age                                      0
Type of Travel                           0
Class                                    0
Flight Distance                          0
Inflight wifi service                    0
Departure/Arrival time convenient        0
Ease of Online booking                   0
Gate location                            0
Food and drink                           0
Online boarding                          0
Seat comfort                             0
Inflight entertainment                   0
On-board service                         0
Leg room service                         0
Baggage handling                         0
Checkin service                          0
Inflight service                         0
Cleanliness                              0
Departure Delay in Minutes               0
Arrival Delay in Minutes               256
id                                   83123
dtype: int64

In [6]:
mean_values=x_train['Arrival Delay in Minutes'].mean()

In [9]:
x_train['Arrival Delay in Minutes']=x_train['Arrival Delay in Minutes'].fillna(mean_values)

In [10]:
x_test.isnull().sum()

ID                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Ease of Online booking                0
Gate location                         0
Food and drink                        0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
On-board service                      0
Leg room service                      0
Baggage handling                      0
Checkin service                       0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
Arrival Delay in Minutes             72
id                                    0
dtype: int64

In [11]:
drop_col=['id']

In [14]:
x_train_drop=x_train.drop(columns=drop_col)
x_test_drop=x_test.drop(columns=drop_col)

## 5. 학습

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [19]:
x_train_dummies=pd.get_dummies(x_train_drop)

In [22]:
y=y_train['satisfaction']

In [23]:
x_test_dummies=pd.get_dummies(x_test_drop)
x_test_dummies=x_test_dummies[x_train_dummies.columns]

In [24]:
X_train, X_validation, Y_train, Y_validation=train_test_split(x_train_dummies,y,test_size=0.33, random_state=42,stratify=y)

In [25]:
rf=RandomForestClassifier(random_state=42)
rf.fit(X_train,Y_train)

RandomForestClassifier(random_state=42)

In [17]:
import sklearn.metrics
from sklearn.metrics import accuracy_score, f1_score, recall_score, roc_auc_score, precision_score

In [26]:
predict_train_label=rf.predict(X_train)
predict_train_proba=rf.predict_proba(X_train)[:,1]

In [ ]:
predict_validation_label=rf.predict(X_validation)
predict_validation_proba=rf.predict_proba(X_train)[:,1]