# DB에 저장된 상장기업 정보 불러오기

In [22]:
import time
import requests
from bs4 import BeautifulSoup as bs
from sqlalchemy import create_engine
import pymysql
pymysql.install_as_MySQLdb()
import pandas as pd
from datetime import datetime

In [80]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")
conn = engine.connect()

In [81]:
data = pd.read_sql("stock_company_info_2025_04_04", con=conn)
conn.close()

# Npay증권에서 종목코드로 주가 조회 후 수집하기

In [26]:
stock_code = data['종목코드'].apply(lambda x: x+"0")
stock_code

0       448900
1       481070
2       101970
3       462860
4       444530
         ...
2756    000100
2757    000120
2758    000050
2759    000700
2760    003480
Name: 종목코드, Length: 2761, dtype: object

In [27]:
import time
import requests
from bs4 import BeautifulSoup as bs

In [29]:
url =f"https://finance.naver.com/item/main.naver?code=005930"
r = requests.get(url)
# print(r.status_code, f"{idx}/{len(stock_code)-1} 작업중", end="\r")
soup = bs(r.content, 'lxml')

In [30]:
soup.select_one("dl.blind")

<dl class="blind">
<dt>종목 시세 정보</dt>
<dd>2025년 04월
        08일 09시
        21분 기준 장중</dd>
<dd>종목명 삼성전자</dd>
<dd>종목코드 005930 코스피</dd>
<dd>현재가 54,500 전일대비 상승 1,300
            플러스
            2.44 퍼센트
        </dd>
<dd>전일가 53,200</dd>
<dd>시가 55,000</dd>
<dd>고가 55,300</dd>
<dd>상한가 69,100</dd>
<dd>저가 54,400</dd>
<dd>하한가 37,300</dd>
<dd>거래량 4,619,959</dd>
<dd>거래대금 253,319백만</dd>
</dl>

In [72]:
stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
change = -int(change[1].replace("\n", "").replace(",", "")) if change[0] == '하락' else int(change[1].replace("\n", "").replace(",", ""))
percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
percent = percent.replace("플러스", "").replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "")
yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
hi = int(soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", ""))
top = int(soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", ""))
low = int(soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", ""))
bottom = int(soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", ""))
volume = int(soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", ""))
result = stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume
result

('삼성전자', 54500, 1300, '2.44%', 53200, 55300, 69100, 54400, 37300, 4619959)

In [125]:
final_result = []
for idx, code in enumerate(stock_code):
    url =f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url)
    print(r.status_code, f"{idx}/{len(stock_code)-1} 작업중", end="\r")
    soup = bs(r.content, 'lxml')
    # 종목명
    stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
    # 현재가
    today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
    # 변동금액
    change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
    change = -int(change[1].replace(",", "").replace("\n,,", "")) if change[0] == "하락" else int(change[1].replace(",", "").replace("\n", ""))
    # 변동률
    percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
    percent = percent.replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "").replace("플러스", "")
    # 전일가
    yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
    # 고가
    hi = soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", "")
    # 상한가
    top = soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", "")
    # 저가
    low = soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", "")
    # 하한가
    bottom = soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", "")
    # 거래량
    volume = soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", "")

    result = (code, stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume)
    final_result.append(result)
    time.sleep(5)
    
columns = ["종목코드", "종목명", "현재가", "변동금액", "변동률", "전일가",
           "고가", "상한가", "저가", "하한가", "거래량" ]    
df = pd.DataFrame(final_result, columns=columns)
df

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,448900,한국피아이엠,13870,-2230,-13.85%,16100,17720,20900,13690,11270,7378280
1,481070,에이유브랜즈,14370,-2590,-15.27%,16960,16130,22000,14350,11880,709156

In [134]:
from datetime import datetime
today = datetime.today()
date = f"{today.year}_{today.month:02d}"
print(date)

2025_04

In [137]:
engine = create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")
conn = engine.connect()
df.to_sql(f'stock_price_{today.year}_{today.month:02d}', con=conn,  if_exists="append", index=False)
conn.close()

# 데이터 수집과 동시에 DB에 저장하기

In [151]:
import time
import requests
from bs4 import BeautifulSoup as bs

In [153]:
def year_month():
    from datetime import datetime
    today = datetime.today()
    return today.year, today.month

In [77]:
from datetime import datetime
today = datetime.today()
print(today.year)
print(f"{today.month:02d}")

2025
04

In [78]:
for idx, code in enumerate(stock_code[:2]):
    url =f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url)
    print(r.status_code, f"{idx}/{len(stock_code)-1} 작업중", end="\r")
    soup = bs(r.content, 'lxml')
    # 종목명
    stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
    # 현재가
    today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
    # 변동금액
    change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
    change = -int(change[1].replace(",", "").replace("\n,,", "")) if change[0] == "하락" else int(change[1].replace(",", "").replace("\n", ""))
    # 변동률
    percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
    percent = percent.replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "").replace("플러스", "")
    # 전일가
    yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
    # 고가
    hi = soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", "")
    # 상한가
    top = soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", "")
    # 저가
    low = soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", "")
    # 하한가
    bottom = soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", "")
    # 거래량
    volume = soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", "")

    result = (code, stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume)
    columns = ["종목코드", "종목명", "현재가", "변동금액", "변동률", "전일가",
           "고가", "상한가", "저가", "하한가", "거래량"  ]    
    df = pd.DataFrame([result], columns=columns)
    
    # 오늘기준 연도, 달 출력
    from datetime import datetime
    today = datetime.today()
    year = today.year
    month = today.month
    
    # Database 쿼리창 오픈
    engine = create_engine("mysql+pymysql://root:1234@localhost:3306/stock_info")
    conn = engine.connect()
    df.to_sql(f'stock_price_{year}_{month:02d}', con=conn,  if_exists="append", index=False)
    conn.close()
    print(f"{idx}/{len(stock_code)-1} {stock_name}DB 저장 완료", end="\r")
    time.sleep(5)

In [163]:
for idx, code in enumerate(stock_code):
    url =f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url)
    print(r.status_code, f"{idx+1}/{len(stock_code)} {code} 작업중", end="\r")
    soup = bs(r.content, 'lxml')
    # 종목명
    stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
    # 현재가
    today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
    # 변동금액
    change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
    change = -int(change[1].replace(",", "").replace("\n,,", "")) if change[0] == "하락" else int(change[1].replace(",", "").replace("\n", ""))
    # 변동률
    percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
    percent = percent.replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "").replace("플러스", "")
    # 전일가
    yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
    # 고가
    hi = soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", "")
    # 상한가
    top = soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", "")
    # 저가
    low = soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", "")
    # 하한가
    bottom = soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", "")
    # 거래량
    volume = soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", "")

    result = (code, stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume)
    columns = ["종목코드", "종목명", "현재가", "변동금액", "변동률", "전일가",
           "고가", "상한가", "저가", "하한가", "거래량"  ]    
    df = pd.DataFrame([result], columns=columns)
    # 오늘기준 연도, 달 출력
    year, month = year_month()
    # Database 쿼리창 오픈
#     conn = dbconnect()
#     df.to_sql(f'stock_price_{year}_{month:02d}', con=conn,  if_exists="append", index=False)
#     conn.close()
    print(f"{idx+1}/{len(stock_code)} {stock_name}DB 저장 완료", end="\r")
    time.sleep(5)

KeyboardInterrupt:

# 함수형 프로그래밍으로 코드 변경하기

In [2]:
import time
import requests
from bs4 import BeautifulSoup as bs

In [18]:
def stock_info_get(code):
    url =f"https://finance.naver.com/item/main.naver?code={code}"
    r = requests.get(url, timeout=1)
    print(r.status_code, f"{idx+1}/{len(stock_code)} {code} 작업중", end="\r")
    soup = bs(r.text, 'lxml')
#     print(soup)
    # 종목명
    stock_name = soup.select_one("dl.blind > dd:nth-child(3)").text[4:]
    # 현재가
    today_price = int(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[1].replace(",", ""))
    # 변동금액
    change = soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[3:5]
    change = -int(change[1].replace(",", "").replace("\n,,", "")) if change[0] == "하락" else int(change[1].replace(",", "").replace("\n", ""))
    # 변동률
    percent = "".join(soup.select_one("dl.blind > dd:nth-child(5)").text.split(" ")[16:30])
    percent = percent.replace("마이너스", "-").replace("퍼센트", "%").replace("\n", "").replace("플러스", "")
    # 전일가
    yester_price = int(soup.select_one("dl.blind > dd:nth-child(6)").text[4:].replace(",", ""))
    # 고가
    hi = soup.select_one("dl.blind > dd:nth-child(8)").text[3:].replace(",", "")
    # 상한가
    top = soup.select_one("dl.blind > dd:nth-child(9)").text[4:].replace(",", "")
    # 저가
    low = soup.select_one("dl.blind > dd:nth-child(10)").text[3:].replace(",", "")
    # 하한가
    bottom = soup.select_one("dl.blind > dd:nth-child(11)").text[4:].replace(",", "")
    # 거래량
    volume = soup.select_one("dl.blind > dd:nth-child(12)").text[4:].replace(",", "")

    result = (code, stock_name, today_price, change, percent, yester_price, hi, top, low, bottom, volume)
    columns = ["종목코드", "종목명", "현재가", "변동금액", "변동률", "전일가",
           "고가", "상한가", "저가", "하한가", "거래량"  ]    
    df = pd.DataFrame([result], columns=columns)
    # 오늘기준 연도, 달 출력
    time.sleep(5)
    return df, stock_name

In [83]:
from dbio import *

In [84]:
stock_code = stock_codes()
for idx, code in enumerate(stock_code):
    print(f"{idx}/{len(stock_code)-1} {code} 작업중", end="\r")
    df, stock_name = stock_info_get(code)
    to_stock_db(idx, code, stock_name, df)
    print(stock_name)
    display(df)

한국피아이엠피아이엠DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,448900,한국피아이엠,14150,280,2.02%,13870,15790,18030,13900,9710,2247795

에이유브랜즈유브랜즈DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,481070,에이유브랜즈,14220,-150,-1.04%,14370,15190,18680,14145,10060,268615

우양에이치씨에이치씨DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,101970,우양에이치씨,17780,1130,6.79%,16650,18190,21600,17220,11660,97763

더즌6 더즌DB 저장 완료860 작업중

     종목코드 종목명   현재가  변동금액     변동률   전일가    고가    상한가    저가   하한가      거래량
0  462860  더즌  7700  -420  -5.17%  8120  7870  10550  7450  5690  1364140

심플랫폼심플랫폼DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가     거래량
0  444530  심플랫폼  11110   140  1.28%  10970  11510  14260  10960  7680  360948

티엑스알로보틱스로보틱스DB 저장 완료중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,484810,티엑스알로보틱스,19880,-320,-1.58%,20200,21100,26250,19680,14150,554274

한텍6 한텍DB 저장 완료070 작업중

     종목코드 종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가      거래량
0  098070  한텍  32100  2350  7.90%  29750  33800  38650  31200  20850  2850587

한화플러스제5호스팩5호스팩DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  498390  한화플러스제5호스팩  1979     1  0.05%  1978  1983  2570  1979  1385  10404

씨케이솔루션이솔루션DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,480370,씨케이솔루션,12290,-240,-1.92%,12530,12830,16280,12230,8780,130621

서울보증보험울보증보험DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,031210,서울보증보험,31800,-50,-0.16%,31850,32450,41400,31600,22300,92571

에스엠씨지에스엠씨지DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가     거래량
0  460870  에스엠씨지  3335    15  0.45%  3320  3700  4315  3295  2325  187470

엠디바이스엠디바이스DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액     변동률   전일가    고가    상한가    저가   하한가     거래량
0  226590  엠디바이스  8000  -170  -2.08%  8170  8510  10620  7950  5720  197515

대진첨단소재진첨단소재DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,393970,대진첨단소재,12310,110,0.90%,12200,13050,15860,12230,8540,1168357

에르코스 에르코스DB 저장 완료0 작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,435570,에르코스,19890,4590,30.00%,15300,19890,19890,18300,10710,535526

엘케이켐 엘케이켐DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  489500  엘케이켐  23550   200  0.86%  23350  24400  30350  23400  16350  42642

위너스6 위너스DB 저장 완료60 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가     거래량
0  479960  위너스  16660   330  2.02%  16330  17150  21200  16500  11440  159074

모티브링크모티브링크DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가     거래량
0  463480  모티브링크  13090   450  3.56%  12640  13500  16430  12810  8850  636755

동국생명과학국생명과학DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액     변동률   전일가    고가    상한가    저가   하한가    거래량
0  303810  동국생명과학  9170   -30  -0.33%  9200  9370  11960  9130  6440  63190

오름테라퓨틱름테라퓨틱DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,475830,오름테라퓨틱,24900,50,0.20%,24850,25850,32300,24450,17400,241087

동방메디컬동방메디컬DB 저장 완료 작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,240550,동방메디컬,10530,-220,-2.05%,10750,11130,13970,10140,7530,933205

아이에스티이이에스티이DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가     거래량
0  212710  아이에스티이  8860   250  2.90%  8610  9170  11190  8730  6030  139178

LG씨엔에스G씨엔에스DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,064400,LG씨엔에스,49150,800,1.65%,48350,50200,62800,48800,33850,111753

아이지넷 아이지넷DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  462980  아이지넷  2995    45  1.53%  2950  3030  3835  2955  2065  27395

피아이이 피아이이DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가     거래량
0  452450  피아이이  7640    80  1.06%  7560  7960  9820  7560  5300  472799

삼양엔씨켐삼양엔씨켐DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  482630  삼양엔씨켐  17150   130  0.76%  17020  17660  22100  16940  11920  65043

데이원컴퍼니이원컴퍼니DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가      거래량
0  373160  데이원컴퍼니  8350   500  6.37%  7850  8940  10200  7450  5500  2206376

아스테라시스스테라시스DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  450950  아스테라시스  7730   230  3.07%  7500  7900  9750  7540  5250  94142

와이즈넛 와이즈넛DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률   전일가     고가    상한가    저가   하한가     거래량
0  096250  와이즈넛  10810   960  9.75%  9850  11430  12800  9910  6900  352738

미트박스 미트박스DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액     변동률    전일가     고가    상한가     저가   하한가     거래량
0  475460  미트박스  13150  -690  -4.99%  13840  13150  17990  13000  9690  110796

유안타제17호스팩17호스팩DB 저장 완료

     종목코드        종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  493790  유안타제17호스팩  1987     8  0.40%  1979  1988  2570  1982  1386  1615

블랙야크아이앤씨크아이앤씨DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  478560  블랙야크아이앤씨  3810    45  1.20%  3765  3930  4890  3785  2640  16804

오션스바이오션스바이오DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  332190  오션스바이오  3000     0  0.00%  3000  3000  3450  3000  2550   0

엠에프씨 엠에프씨DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  432980  엠에프씨  3770    85  2.31%  3685  3810  4790  3575  2580  7738

파인메딕스파인메딕스DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  387570  파인메딕스  7850   450  6.08%  7400  8060  9620  7650  5180  60157

쓰리에이로직스에이로직스DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가     거래량
0  177900  쓰리에이로직스  7890   180  2.33%  7710  8190  10020  7850  5400  216687

GS피앤엘GS피앤엘DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액     변동률    전일가     고가    상한가     저가    하한가   거래량
0  499790  GS피앤엘  17060  -210  -1.22%  17270  17490  22450  17020  12090  7961

신한제14호스팩14호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  487360  신한제14호스팩  1994    -1  -0.05%  1995  1995  2590  1993  1397  760

유비씨6 유비씨DB 저장 완료10 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가 거래량
0  495810  유비씨  13120     0  0.00%  13120  13120  15080  13120  11160   0

창대정밀 창대정밀DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  368030  창대정밀  8580     0  0.00%  8580  8580  9860  8580  7300   0

듀켐바이오듀켐바이오DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  176750  듀켐바이오  11600   690  6.32%  10910  11840  14180  11100  7640  84122

키움제10호스팩10호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  487720  키움제10호스팩  2040    -5  -0.24%  2045  2045  2655  2040  1435  229

에스지헬스케어지헬스케어DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  398120  에스지헬스케어  2770   135  5.12%  2635  2790  3425  2670  1845  32007

온코닉테라퓨틱스테라퓨틱스DB 저장 완료중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,476060,온코닉테라퓨틱스,21500,0,0.00%,21500,22950,27950,20950,15050,464676

온코크로스온코크로스DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가     거래량
0  382150  온코크로스  8630   130  1.53%  8500  8930  11050  8540  5950  154815

벡트/6 벡트DB 저장 완료600 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  457600  벡트  2895   140  5.08%  2755  2940  3580  2770  1930  57550

엠앤씨솔루션앤씨솔루션DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,484870,엠앤씨솔루션,75200,2200,3.01%,73000,76700,94900,73400,51100,14323

셀로맥스사이언스스사이언스DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  471820  셀로맥스사이언스  4670    45  0.97%  4625  4740  6010  4620  3240  8565

에이엠시지에이엠시지DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가 거래량
0  495900  에이엠시지  11400     0  0.00%  11400  11400  13110  11400  9690   0

KB제31호스팩31호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  492220  KB제31호스팩  1998     6  0.30%  1992  1998  2585  1988  1395  14752

키움제11호스팩11호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  489480  키움제11호스팩  1996     1  0.05%  1995  1997  2590  1990  1397  1115

KB발해인프라발해인프라DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  415640  KB발해인프라  7520    20  0.27%  7500  7580  9750  7500  5250  5730

디비금융제13호스팩13호스팩DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  489730  디비금융제13호스팩  1996    10  0.50%  1986  1996  2580  1988  1391  7821

교보17호스팩17호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  489210  교보17호스팩  2005     7  0.35%  1998  2005  2595  2005  1399  27

대신밸런스제19호스팩19호스팩DB 저장 완료

     종목코드          종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  482690  대신밸런스제19호스팩  2040    10  0.49%  2030  2040  2635  2040  1425  13

위츠/6 위츠DB 저장 완료100 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  459100  위츠  6130   130  2.17%  6000  6240  7800  6090  4200  14761

유디엠텍 유디엠텍DB 저장 완료0 작업중

     종목코드   종목명  현재가  변동금액    변동률  전일가   고가  상한가   저가  하한가     거래량
0  389680  유디엠텍  642     3  0.47%  639  650  830  637  448  459985

RF시스템즈F시스템즈DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가     거래량
0  474610  RF시스템즈  4170    55  1.34%  4115  4310  5340  4150  2885  105946

사이냅소프트이냅소프트DB 저장 완료작업중

     종목코드     종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  466410  사이냅소프트  11900   300  2.59%  11600  12200  15080  11720  8120  14071

하나34호스팩34호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  484130  하나34호스팩  2015   -15  -0.74%  2030  2030  2635  2015  1425  287

에스켐6 에스켐DB 저장 완료60 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  475660  에스켐  5030   145  2.97%  4885  5060  6350  4920  3420  4739

엠오티6 엠오티DB 저장 완료90 작업중

     종목코드  종목명   현재가  변동금액     변동률   전일가    고가    상한가    저가   하한가     거래량
0  413390  엠오티  8620   -10  -0.12%  8630  9050  11210  8430  6050  228256

신한제15호스팩15호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  487830  신한제15호스팩  2015     0  0.00%  2015  2015  2615  2010  1415  5557

쓰리빌리언쓰리빌리언DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가     거래량
0  394800  쓰리빌리언  5430   250  4.83%  5180  5450  6730  5330  3630  196169

닷밀/6 닷밀DB 저장 완료580 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  464580  닷밀  4945    45  0.92%  4900  5050  6370  4925  3430  28680

노머스6 노머스DB 저장 완료80 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  473980  노머스  23950     0  0.00%  23950  24950  31100  23800  16800  57088

에어레인 에어레인DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가     거래량
0  163280  에어레인  16660  1010  6.45%  15650  16930  20300  15850  10960  787445

토모큐브 토모큐브DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  475960  토모큐브  14300   570  4.15%  13730  14740  17840  13910  9620  28254

더본코리아더본코리아DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  475560  더본코리아  27400   100  0.37%  27300  27800  35450  27250  19150  12623

에이치이엠파마치이엠파마DB 저장 완료업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,376270,에이치이엠파마,22900,1000,4.57%,21900,23000,28450,22400,15350,14499

에이럭스 에이럭스DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가    거래량
0  475580  에이럭스  9550   230  2.47%  9320  9770  12110  9420  6530  44334

탑런토탈솔루션토탈솔루션DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가   거래량
0  336680  탑런토탈솔루션  8200     0  0.00%  8200  8330  10660  8190  5740  2026

성우/6 성우DB 저장 완료650 작업중

     종목코드 종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  458650  성우  14040    20  0.14%  14020  14450  18220  13970  9820  27591

유진스팩11호스팩11호DB 저장 완료업중

     종목코드      종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  488060  유진스팩11호  2005    -5  -0.25%  2010  2010  2610  2005  1410  350

타조엔터테인먼트터테인먼트DB 저장 완료중

     종목코드       종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가 거래량
0  476710  타조엔터테인먼트  16800     0  0.00%  16800  16800  19320  16800  14280   0

클로봇6 클로봇DB 저장 완료00 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가     거래량
0  466100  클로봇  17640   260  1.50%  17380  18300  22550  17310  12170  507104

에이치엔에스하이텍에스하이텍DB 저장 완료

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,044990,에이치엔에스하이텍,15120,220,1.48%,14900,15580,19370,14900,10430,1706

웨이비스 웨이비스DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  289930  웨이비스  6910   280  4.22%  6630  7100  8610  6800  4650  40498

씨메스6 씨메스DB 저장 완료00 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  475400  씨메스  20550   400  1.99%  20150  21000  26150  20350  14150  66107

한켐/6 한켐DB 저장 완료370 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가    거래량
0  457370  한켐  8660   260  3.10%  8400  8770  10920  8450  5880  31618

루미르6 루미르DB 저장 완료70 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  474170  루미르  7750   270  3.61%  7480  8120  9720  7700  5240  60167

와이제이링크이제이링크DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  209640  와이제이링크  6880   270  4.08%  6610  6980  8590  6670  4630  37446

인스피언 인스피언DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  465480  인스피언  5680   160  2.90%  5520  5730  7170  5580  3870  28257

셀비온6 셀비온DB 저장 완료30 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  308430  셀비온  16880   420  2.55%  16460  17290  21350  16640  11530  63498

제닉스6 제닉스DB 저장 완료20 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  381620  제닉스  7100   210  3.05%  6890  7270  8950  7030  4830  73653

차이커뮤니케이션뮤니케이션DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  351870  차이커뮤니케이션  7180   160  2.28%  7020  7350  9120  7060  4920  7258

한화비전 한화비전DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가     거래량
0  489790  한화비전  47800  1400  3.02%  46400  48900  60300  47250  32500  478189

KB제30호스팩30호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  486630  KB제30호스팩  2010     0  0.00%  2010  2020  2610  2005  1410  3499

아이언디바이스언디바이스DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가     거래량
0  464500  아이언디바이스  2835   175  6.58%  2660  2930  3455  2715  1865  157499

미래에셋비전스팩7호전스팩7호DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  482680  미래에셋비전스팩7호  1973     0  0.00%  1973  1985  2560  1973  1382  6469

아이비젼웍스이비젼웍스DB 저장 완료작업중

     종목코드     종목명  현재가  변동금액    변동률  전일가   고가   상한가   저가  하한가    거래량
0  469750  아이비젼웍스  875     7  0.81%  868  889  1128  865  608  63123

아이스크림미디어크림미디어DB 저장 완료중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,461300,아이스크림미디어,13690,440,3.32%,13250,13810,17220,13200,9280,43069

이엔셀6 이엔셀DB 저장 완료70 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  456070  이엔셀  13300   290  2.23%  13010  13550  16910  13120  9110  33306

M836 M83DB 저장 완료80 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  476080  M83  12330   540  4.58%  11790  12480  15320  12020  8260  65523

대신밸런스제18호스팩18호스팩DB 저장 완료

     종목코드          종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  478780  대신밸런스제18호스팩  2050     5  0.24%  2045  2070  2655  2050  1435  3615

티디에스팜티디에스팜DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  464280  티디에스팜  11280   290  2.64%  10990  11410  14280  11030  7700  30859

넥스트바이오메디컬이오메디컬DB 저장 완료

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,389650,넥스트바이오메디컬,38450,2450,6.81%,36000,38900,46800,37050,25200,53577

케이쓰리아이이쓰리아이DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  431190  케이쓰리아이  3990    65  1.66%  3925  4060  5100  3900  2750  10717

전진건설로봇진건설로봇DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,079900,전진건설로봇,38450,1950,5.34%,36500,38900,47450,37250,25550,61173

유라클6 유라클DB 저장 완료40 작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,088340,유라클,31150,-150,-0.48%,31300,33500,40650,29100,21950,1165736

교보16호스팩보16호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  482520  교보16호스팩  2030     0  0.00%  2030  2035  2635  2030  1425  41

뱅크웨어글로벌크웨어글로벌DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  199480  뱅크웨어글로벌  4210   130  3.19%  4080  4260  5300  4110  2860  68614

아이빔테크놀로지빔테크놀로지DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  460470  아이빔테크놀로지  3900   190  5.12%  3710  3935  4820  3715  2600  30144

피앤에스미캐닉스에스미캐닉스DB 저장 완료중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,460940,피앤에스미캐닉스,10600,530,5.26%,10070,10650,13090,10250,7050,39666

HS효성6 HS효성DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가   거래량
0  487570  HS효성  37500   650  1.76%  36850  37800  47900  37000  25800  1500

산일전기6 산일전기DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가     거래량
0  062040  산일전기  47300  1300  2.83%  46000  48150  59800  46900  32200  117970

엔에이치스팩31호치스팩31호DB 저장 완료

     종목코드        종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가  거래량
0  481890  엔에이치스팩31호  2005    10  0.50%  1995  2005  2590  1995  1397  484

에스케이증권제13호스팩제13호스팩DB 저장 완료

     종목코드           종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  473950  에스케이증권제13호스팩  2025     0  0.00%  2025  2030  2630  2025  1420   7

엑셀세라퓨틱스셀세라퓨틱스DB 저장 완료업중

     종목코드      종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가      거래량
0  373110  엑셀세라퓨틱스  4195   965  29.88%  3230  4195  4195  3480  2265  1078770

이베스트스팩6호스트스팩6호DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가  거래량
0  478110  이베스트스팩6호  2005     6  0.30%  1999  2010  2595  2005  1400  112

시프트업6 시프트업DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  462870  시프트업  47650   750  1.60%  46900  48300  60900  47000  32850  28444

하스1/6 하스DB 저장 완료330 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  450330  하스  7680   200  2.67%  7480  7700  9720  7520  5240  12399

이노스페이스이노스페이스DB 저장 완료작업중

     종목코드     종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가   거래량
0  462350  이노스페이스  17830   520  3.00%  17310  18000  22500  17550  12120  5999

신한글로벌액티브리츠벌액티브리츠DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  481850  신한글로벌액티브리츠  1515     0  0.00%  1515  1525  1969  1510  1061  3516

에이치브이엠에이치브이엠DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,295310,에이치브이엠,17190,360,2.14%,16830,17550,21850,17060,11790,43973

팡스카이6 팡스카이DB 저장 완료0 작업중

     종목코드   종목명  현재가  변동금액    변동률  전일가 고가  상한가 저가  하한가 거래량
0  266350  팡스카이  398     0  0.00%  398  0  457  0  339   0

하이젠알앤엠하이젠알앤엠DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,160190,하이젠알앤엠,26000,650,2.56%,25350,26700,32950,25650,17750,46050

한국제15호스팩제15호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  479880  한국제15호스팩  2025     5  0.25%  2020  2025  2625  2015  1415  4027

에스오에스랩에스오에스랩DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가     거래량
0  464080  에스오에스랩  8860   210  2.43%  8650  9070  11240  8790  6060  139431

미래에셋비전스팩6호비전스팩6호DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  478440  미래에셋비전스팩6호  2000     5  0.25%  1995  2000  2590  1994  1397  1157

에이치엠씨제7호스팩씨제7호스팩DB 저장 완료

     종목코드         종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가   거래량
0  477340  에이치엠씨제7호스팩  1980    -5  -0.25%  1985  1985  2580  1962  1390  6437

파라다이스 파라다이스DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  034230  파라다이스  11290   170  1.53%  11120  11340  14450  11160  7790  95357

한중엔시에스한중엔시에스DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,107640,한중엔시에스,22050,1000,4.75%,21050,22050,27350,21350,14750,18426

KB제29호스팩제29호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가  거래량
0  478390  KB제29호스팩  2045    10  0.49%  2035  2045  2645  2040  1425  133

미래에셋비전스팩5호비전스팩5호DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  477470  미래에셋비전스팩5호  2015     0  0.00%  2015  2035  2615  2015  1415  81

씨어스테크놀로지스테크놀로지DB 저장 완료중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,458870,씨어스테크놀로지,11850,100,0.85%,11750,12180,15270,11770,8230,8968

한국제14호스팩제14호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  477530  한국제14호스팩  3325   125  3.91%  3200  3390  4160  3200  2240  38684

DB금융스팩12호융스팩12호DB 저장 완료

     종목코드        종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  477760  DB금융스팩12호  2055     5  0.24%  2050  2060  2665  2050  1435  3180

라메디텍6 라메디텍DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  462510  라메디텍  7690   320  4.34%  7370  7720  9580  7450  5160  16745

그리드위즈 그리드위즈DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액     변동률    전일가     고가    상한가     저가   하한가   거래량
0  453450  그리드위즈  12910   -10  -0.08%  12920  13200  16790  12830  9050  5412

다원넥스뷰 다원넥스뷰DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  323350  다원넥스뷰  5930   130  2.24%  5800  5930  7540  5810  4060  19242

미래에셋비전스팩4호비전스팩4호DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  477380  미래에셋비전스팩4호  2000     9  0.45%  1991  2005  2585  1990  1394  2630

노브랜드6 노브랜드DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  145170  노브랜드  5250   120  2.34%  5130  5310  6660  5210  3600  31687

KB제28호스팩제28호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  476470  KB제28호스팩  2180     5  0.23%  2175  2195  2825  2175  1525  7788

아이씨티케이아이씨티케이DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,456010,아이씨티케이,13180,770,6.20%,12410,13900,16130,12990,8690,1574295

HD현대마린솔루션대마린솔루션DB 저장 완료

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,443060,HD현대마린솔루션,141500,3400,2.46%,138100,143600,179500,140000,96700,16667

에스케이증권제12호스팩제12호스팩DB 저장 완료

     종목코드           종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  473000  에스케이증권제12호스팩  2060     0  0.00%  2060  2065  2675  2050  1445   3

코칩7/6 코칩DB 저장 완료730 작업중

     종목코드 종목명    현재가  변동금액    변동률   전일가     고가    상한가    저가   하한가   거래량
0  126730  코칩  10020   220  2.24%  9800  10200  12740  9880  6860  9293

민테크/6 민테크DB 저장 완료00 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  452200  민테크  3705    70  1.93%  3635  3785  4725  3615  2545  26715

카티스/6 카티스DB 저장 완료30 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  140430  카티스  1737    19  1.11%  1718  1769  2230  1722  1203  10766

디앤디파마텍디앤디파마텍DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,347850,디앤디파마텍,42300,500,1.20%,41800,43250,54300,41250,29300,42564

유안타제16호스팩제16호스팩DB 저장 완료

     종목코드        종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가   거래량
0  474490  유안타제16호스팩  1990    -6  -0.30%  1996  2005  2590  1928  1398  1745

제일엠앤에스제일엠앤에스DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가 고가   상한가 저가   하한가 거래량
0  412540  제일엠앤에스  3935     0  0.00%  3935  0  5110  0  2755   0

삐아3/6 삐아DB 저장 완료250 작업중

     종목코드 종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가     거래량
0  451250  삐아  10860    10  0.09%  10850  11230  14100  10770  7600  153059

하나33호스팩나33호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  475250  하나33호스팩  2080   -10  -0.48%  2090  2100  2715  2080  1465  865

신한제13호스팩제13호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가   거래량
0  474930  신한제13호스팩  2105   -30  -1.41%  2135  2130  2775  2100  1495  1271

신한제12호스팩제12호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  474660  신한제12호스팩  2075    10  0.48%  2065  2095  2680  2050  1450  53

아이엠비디엑스이엠비디엑스DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가    거래량
0  461030  아이엠비디엑스  8600   220  2.63%  8380  8690  10890  8450  5870  16808

SK이터닉스SK이터닉스DB 저장 완료작업중

     종목코드     종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  475150  SK이터닉스  13990   320  2.34%  13670  14110  17770  13710  9570  57127

하나32호스팩나32호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  475240  하나32호스팩  2105   -20  -0.94%  2125  2125  2760  2095  1490  901

엔젤로보틱스엔젤로보틱스DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,455900,엔젤로보틱스,21250,150,0.71%,21100,21800,27400,21150,14800,18015

제이투케이바이오투케이바이오DB 저장 완료중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,420570,제이투케이바이오,10980,-330,-2.92%,11310,11880,14700,10670,7920,76221

삼현2/6 삼현DB 저장 완료730 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가    거래량
0  437730  삼현  9270   200  2.21%  9070  9390  11790  9090  6350  70249

오상헬스케어오상헬스케어DB 저장 완료작업중

     종목코드     종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가   거래량
0  036220  오상헬스케어  12460   280  2.30%  12180  12490  15830  12310  8530  8561

케이엔알시스템이엔알시스템DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  199430  케이엔알시스템  6740   210  3.22%  6530  6870  8480  6600  4580  20721

비엔케이제2호스팩이제2호스팩DB 저장 완료

     종목코드        종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  473370  비엔케이제2호스팩  1980     3  0.15%  1977  1995  2570  1977  1384  1776

하나31호스팩나31호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  469900  하나31호스팩  2005    13  0.65%  1992  2005  2585  1995  1395  2204

에스케이증권제11호스팩제11호스팩DB 저장 완료

     종목코드           종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  472230  에스케이증권제11호스팩  2025     5  0.25%  2020  2030  2625  2015  1415   3

유안타제15호스팩제15호스팩DB 저장 완료

     종목코드        종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가   거래량
0  473050  유안타제15호스팩  1984   -11  -0.55%  1995  1995  2590  1983  1397  7945

유진스팩10호진스팩10호DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  468760  유진스팩10호  2095    15  0.72%  2080  2115  2700  2070  1460  5236

에이피알6 에이피알DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가     거래량
0  278470  에이피알  63000   800  1.29%  62200  64400  80800  62300  43600  131890

이에이트6 이에이트DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  418620  이에이트  2535   125  5.19%  2410  2565  3130  2470  1690  39510

코셈2/6 코셈DB 저장 완료350 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  360350  코셈  6510    40  0.62%  6470  6760  8410  6490  4530  3897

케이웨더6 케이웨더DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  068100  케이웨더  2785    75  2.77%  2710  2980  3520  2720  1900  41023

사피엔반도체사피엔반도체DB 저장 완료작업중

     종목코드     종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  452430  사피엔반도체  13900   430  3.19%  13470  14100  17510  13670  9430  18616

에스피소프트에스피소프트DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  443670  에스피소프트  6250   210  3.48%  6040  6310  7850  6100  4230  52813

스튜디오삼익스튜디오삼익DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가   거래량
0  415380  스튜디오삼익  7940     0  0.00%  7940  8090  10320  7760  5560  7463

신영스팩10호영스팩10호DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  472220  신영스팩10호  2100     5  0.24%  2095  2115  2720  2095  1470  1569

폰드그룹6 폰드그룹DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  472850  폰드그룹  5450    70  1.30%  5380  5560  6990  5310  3770  57143

IBKS제24호스팩제24호스팩DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  469480  IBKS제24호스팩  2085     0  0.00%  2085  2115  2710  2075  1460  1050

레이저옵텍 레이저옵텍DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가     거래량
0  199550  레이저옵텍  9500    60  0.64%  9440  9890  12270  9380  6610  317654

이닉스/6 이닉스DB 저장 완료00 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가   거래량
0  452400  이닉스  8130   230  2.91%  7900  8190  10270  8000  5530  3766

엘앤에프6 엘앤에프DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  066970  엘앤에프  58700  1600  2.80%  57100  59600  74200  57600  40000  78787

포스뱅크6 포스뱅크DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  105760  포스뱅크  5860   110  1.91%  5750  5940  7470  5750  4030  54342

현대힘스6 현대힘스DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  460930  현대힘스  12830   260  2.07%  12570  13170  16340  12630  8800  56917

HB인베스트먼트인베스트먼트DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  440290  HB인베스트먼트  1726    22  1.29%  1704  1743  2215  1706  1193  1738

드림인사이트드림인사이트DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가     거래량
0  362990  드림인사이트  2150   -65  -2.93%  2215  2450  2875  2135  1555  715951

대신밸런스제17호스팩제17호스팩DB 저장 완료

     종목코드          종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  471050  대신밸런스제17호스팩  2130    25  1.19%  2105  2135  2735  2100  1475  6304

우진엔텍6 우진엔텍DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  457550  우진엔텍  14340   440  3.17%  13900  14460  18070  14130  9730  41828

세븐브로이맥주븐브로이맥주DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가  하한가 거래량
0  267080  세븐브로이맥주  1116    19  1.73%  1097  1116  1261  1116  933   2

한빛레이저 한빛레이저DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가     거래량
0  452190  한빛레이저  5410   100  1.88%  5310  5630  6900  5375  3720  555028

포스코DX 포스코DXDB 저장 완료 작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,022100,포스코DX,23800,500,2.15%,23300,24150,30250,23400,16350,288519

DS단석6 DS단석DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  017860  DS단석  20850   200  0.97%  20650  21550  26800  20750  14500  69908

IBKS제23호스팩제23호스팩DB 저장 완료

     종목코드         종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  467930  IBKS제23호스팩  2090   -20  -0.95%  2110  2120  2740  2090  1480  411

하나30호스팩나30호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  469880  하나30호스팩  1997     2  0.10%  1995  2005  2590  1995  1397  4700

씨싸이트6 씨싸이트DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  109670  씨싸이트  6350   260  4.27%  6090  6400  7910  6130  4270  7609

블루엠텍6 블루엠텍DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가    거래량
0  439580  블루엠텍  9340   280  3.09%  9060  9440  11770  9120  6350  28035

LS머트리얼즈S머트리얼즈DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가     고가    상한가    저가   하한가    거래량
0  417200  LS머트리얼즈  9950   100  1.02%  9850  10100  12800  9910  6900  78114

케이엔에스 케이엔에스DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률   전일가     고가    상한가     저가   하한가   거래량
0  432470  케이엔에스  10330   520  5.30%  9810  10480  12750  10000  6870  6147

교보15호스팩보15호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가  거래량
0  465320  교보15호스팩  2075     0  0.00%  2075  2085  2695  2075  1455  312

와이바이오로직스바이오로직스DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  338840  와이바이오로직스  5690   210  3.83%  5480  5740  7120  5510  3840  14549

삼성스팩9호삼성스팩9호DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가    거래량
0  468510  삼성스팩9호  1985   -11  -0.55%  1996  2005  2590  1976  1398  15105

에이텀/6 에이텀DB 저장 완료90 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  355690  에이텀  6270   320  5.38%  5950  6530  7730  5920  4170  1324

엔에이치스팩30호치스팩30호DB 저장 완료

     종목코드        종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가   거래량
0  466910  엔에이치스팩30호  1992    -5  -0.25%  1997  2000  2595  1990  1398  6353

에이에스텍 에이에스텍DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가   거래량
0  453860  에이에스텍  18400   480  2.68%  17920  18550  23250  18000  12550  2221

그린리소스 그린리소스DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가    거래량
0  402490  그린리소스  13320   900  7.25%  12420  13410  16140  12530  8700  44546

제이엔비6 제이엔비DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가    거래량
0  452160  제이엔비  4560   -90  -1.94%  4650  4720  6040  4520  3255  11705

한선엔지니어링선엔지니어링DB 저장 완료업중

     종목코드      종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가    거래량
0  452280  한선엔지니어링  6280  -120  -1.87%  6400  6430  8320  6170  4480  46660

동인기연6 동인기연DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가   거래량
0  111380  동인기연  14160   240  1.72%  13920  14290  18090  14000  9750  1073

에코아이6 에코아이DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가   거래량
0  448280  에코아이  19790   890  4.71%  18900  19900  24550  18760  13230  7487

스톰테크6 스톰테크DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  352090  스톰테크  3215    25  0.78%  3190  3230  4145  3195  2235  15133

에코프로머티에코프로머티DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,450080,에코프로머티,51800,1300,2.57%,50500,52700,65600,51000,35400,154236

캡스톤파트너스스톤파트너스DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  452300  캡스톤파트너스  2800    50  1.82%  2750  2820  3575  2745  1925  95691

프로젠/6 프로젠DB 저장 완료60 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  296160  프로젠  5090    90  1.80%  5000  5160  5750  5000  4250  8232

에스와이스틸텍스와이스틸텍DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가     거래량
0  365330  에스와이스틸텍  4770   135  2.91%  4635  4810  6020  4685  3245  134089

에이직랜드 에이직랜드DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  445090  에이직랜드  25600   850  3.43%  24750  26000  32150  25300  17350  16937

한국제13호스팩제13호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  464440  한국제13호스팩  2120    20  0.95%  2100  2120  2730  2095  1470  23

메가터치6 메가터치DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  446540  메가터치  3395    85  2.57%  3310  3460  4300  3345  2320  80795

비아이매트릭스아이매트릭스DB 저장 완료업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,413640,비아이매트릭스,10600,510,5.05%,10090,10750,13110,10180,7070,52239

컨텍9/6 컨텍DB 저장 완료760 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가    거래량
0  451760  컨텍  9140   180  2.01%  8960  9320  11640  9010  6280  19761

큐로셀/6 큐로셀DB 저장 완료20 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  372320  큐로셀  25250   400  1.61%  24850  25600  32300  24850  17400  12293

쏘닉스/6 쏘닉스DB 저장 완료80 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  088280  쏘닉스  2305    95  4.30%  2210  2385  2870  2250  1550  3290

KB제27호스팩제27호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  464680  KB제27호스팩  1987     0  0.00%  1987  1996  2580  1986  1391  1288

세니젠/6 세니젠DB 저장 완료60 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  188260  세니젠  2370     5  0.21%  2365  2440  3070  2365  1660  3717

신시웨이6 신시웨이DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  290560  신시웨이  6330    60  0.96%  6270  6460  8150  6080  4390  2525

유진테크놀로지진테크놀로지DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  240600  유진테크놀로지  4200    70  1.69%  4130  4265  5360  4140  2895  9077

유투바이오 유투바이오DB 저장 완료 작업중

     종목코드    종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  221800  유투바이오  3065   120  4.07%  2945  3085  3825  2980  2065  36420

퀄리타스반도체리타스반도체DB 저장 완료업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,432720,퀄리타스반도체,11720,600,5.40%,11120,12030,14450,11520,7790,112154

미쥬8/6 미쥬DB 저장 완료020 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가 거래량
0  351020  미쥬  7500     0  0.00%  7500  7500  8620  7500  6380   0

워트9/6 워트DB 저장 완료470 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  396470  워트  6900   290  4.39%  6610  6980  8590  6800  4630  32061

에스엘에스바이오엘에스바이오DB 저장 완료중

     종목코드       종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가    거래량
0  246250  에스엘에스바이오  1477   -13  -0.87%  1490  1527  1937  1477  1043  84287

신성에스티 신성에스티DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가    거래량
0  416180  신성에스티  26800  1000  3.88%  25800  27150  33500  26400  18100  26372

퓨릿2/6 퓨릿DB 저장 완료180 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  445180  퓨릿  5300    70  1.34%  5230  5380  6790  5230  3670  16887

바이오텐6 바이오텐DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액      변동률   전일가    고가   상한가    저가   하한가  거래량
0  289170  바이오텐  3630  -640  -14.99%  4270  4270  4910  3630  3630  869

에이치엠씨제6호스팩씨제6호스팩DB 저장 완료

     종목코드         종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  462020  에이치엠씨제6호스팩  2015    -5  -0.25%  2020  2020  2625  2015  1415  754

아이엠티6 아이엠티DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가     거래량
0  451220  아이엠티  10240   120  1.19%  10120  10630  13150  10160  7090  100280

레뷰코퍼레이션뷰코퍼레이션DB 저장 완료업중

     종목코드      종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가   거래량
0  443250  레뷰코퍼레이션  10680    10  0.09%  10670  10840  13870  10530  7470  5557

두산로보틱스두산로보틱스DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,454910,두산로보틱스,41900,300,0.72%,41600,42650,54000,41150,29150,150930

신한제11호스팩제11호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  452980  신한제11호스팩  1994     1  0.05%  1993  1996  2590  1994  1396  11369

한싹9/6 한싹DB 저장 완료690 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  430690  한싹  4165   170  4.26%  3995  4200  5190  4070  2800  57207

밀리의서재 밀리의서재DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액     변동률    전일가     고가    상한가     저가   하한가    거래량
0  418470  밀리의서재  11570   -80  -0.69%  11650  11970  15140  11490  8160  23702

인스웨이브시스템즈이브시스템즈DB 저장 완료

     종목코드        종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가     거래량
0  450520  인스웨이브시스템즈  4570    40  0.88%  4530  4595  5880  4365  3175  277434

우듬지팜6 우듬지팜DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가  하한가     거래량
0  403490  우듬지팜  1353    10  0.74%  1343  1374  1745  1339  941  181853

코어라인소프트어라인소프트DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  384470  코어라인소프트  5780   110  1.94%  5670  5970  7370  5670  3970  22596

STX그린로지스X그린로지스DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가     거래량
0  465770  STX그린로지스  8380   110  1.33%  8270  8590  10750  8190  5790  124328

상상인제4호스팩인제4호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  452670  상상인제4호스팩  2005     0  0.00%  2005  2010  2605  2000  1405  2502

율촌6/6 율촌DB 저장 완료060 작업중

     종목코드 종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가  하한가    거래량
0  146060  율촌  1188    17  1.45%  1171  1189  1522  1143  820  13056

한화플러스제4호스팩스제4호스팩DB 저장 완료

     종목코드         종목명   현재가  변동금액    변동률   전일가 고가   상한가 저가   하한가 거래량
0  455310  한화플러스제4호스팩  2010     0  0.00%  2010  0  2610  0  1410   0

대신밸런스제16호스팩제16호스팩DB 저장 완료

     종목코드          종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  457630  대신밸런스제16호스팩  2080     0  0.00%  2080  2100  2700  2080  1460  6640

유안타제11호스팩제11호스팩DB 저장 완료

     종목코드        종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  444920  유안타제11호스팩  2015    10  0.50%  2005  2015  2605  2005  1405  1678

크라우드웍스크라우드웍스DB 저장 완료작업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,355390,크라우드웍스,11510,2650,29.91%,8860,11510,11510,11510,6210,423372

대신밸런스제15호스팩제15호스팩DB 저장 완료

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,457390,대신밸런스제15호스팩,2735,-20,-0.73%,2755,2810,3580,2720,1930,47581

한국제12호스팩제12호스팩DB 저장 완료중

     종목코드       종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  458610  한국제12호스팩  2110   -15  -0.71%  2125  2135  2760  2110  1490  285

시큐레터6 시큐레터DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가 고가   상한가 저가   하한가 거래량
0  418250  시큐레터  6550     0  0.00%  6550  0  8510  0  4590   0

스마트레이더시스템레이더시스템DB 저장 완료

     종목코드        종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가    거래량
0  424960  스마트레이더시스템  8490   140  1.68%  8350  8900  10850  8430  5850  45637

넥스틸/6 넥스틸DB 저장 완료90 작업중

     종목코드  종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가     거래량
0  092790  넥스틸  11120   170  1.55%  10950  11530  14230  11050  7670  298576

캔버스엔6 캔버스엔DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가     거래량
0  210120  캔버스엔  2540   -80  -3.05%  2620  2690  3405  2450  1835  136994

에스케이증권제10호스팩제10호스팩DB 저장 완료

     종목코드           종목명   현재가  변동금액     변동률   전일가    고가   상한가    저가   하한가  거래량
0  457940  에스케이증권제10호스팩  2055    -5  -0.24%  2060  2070  2675  2055  1445  719

코츠테크놀로지츠테크놀로지DB 저장 완료업중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,448710,코츠테크놀로지,16300,620,3.95%,15680,16430,20350,15840,10980,13030

큐리옥스바이오시스템즈이오시스템즈DB 저장 완료

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,445680,큐리옥스바이오시스템즈,19070,1020,5.65%,18050,19110,23450,18360,12640,48516

하나28호스팩나28호스팩DB 저장 완료업중

     종목코드      종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  454750  하나28호스팩  2010     0  0.00%  2010  2015  2610  2010  1410  3700

NICE평가정보CE평가정보DB 저장 완료중

,종목코드,종목명,현재가,변동금액,변동률,전일가,고가,상한가,저가,하한가,거래량
0,030190,NICE평가정보,11740,230,2.00%,11510,11760,14960,11590,8060,15302

파두2/6 파두DB 저장 완료110 작업중

     종목코드 종목명   현재가  변동금액     변동률   전일가    고가    상한가    저가   하한가    거래량
0  440110  파두  9390  -120  -1.26%  9510  9950  12360  9360  6660  63784

엠아이큐브솔루션이큐브솔루션DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가  거래량
0  373170  엠아이큐브솔루션  7340   230  3.23%  7110  7400  9240  7110  4980  891

시지트로닉스시지트로닉스DB 저장 완료작업중

     종목코드     종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  429270  시지트로닉스  3860    40  1.05%  3820  3940  4965  3820  2675  11076

에피바이오텍에피바이오텍DB 저장 완료작업중

     종목코드     종목명    현재가  변동금액     변동률    전일가     고가    상한가     저가   하한가 거래량
0  446440  에피바이오텍  10900  -100  -0.91%  11000  10900  12650  10900  9350   2

조선내화6 조선내화DB 저장 완료0 작업중

     종목코드   종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가   하한가   거래량
0  462520  조선내화  12350   110  0.90%  12240  12500  15910  12240  8570  1338

에이엘티6 에이엘티DB 저장 완료0 작업중

     종목코드   종목명   현재가  변동금액    변동률   전일가    고가    상한가    저가   하한가    거래량
0  172670  에이엘티  8020   230  2.95%  7790  8200  10120  7920  5460  62647

유안타제14호스팩제14호스팩DB 저장 완료

     종목코드        종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가   거래량
0  450940  유안타제14호스팩  2040     5  0.25%  2035  2040  2645  2020  1425  2036

파로스아이바이오스아이바이오DB 저장 완료중

     종목코드       종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  388870  파로스아이바이오  5740   220  3.99%  5520  5790  7170  5530  3870  11457

길교이앤씨 길교이앤씨DB 저장 완료 작업중

     종목코드    종목명    현재가  변동금액    변동률    전일가     고가    상한가     저가    하한가 거래량
0  456700  길교이앤씨  15000     0  0.00%  15000  15000  17250  15000  12750   0

버넥트/6 버넥트DB 저장 완료00 작업중

     종목코드  종목명   현재가  변동금액    변동률   전일가    고가   상한가    저가   하한가    거래량
0  438700  버넥트  2980    75  2.58%  2905  2990  3775  2910  2035  11974

ReadTimeout: HTTPSConnectionPool(host='finance.naver.com', port=443): Read timed out. (read timeout=1)