In [17]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")


driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )
driver.get("https://www.kebhana.com/cms/rate/index.do?contentUrl=/cms/rate/wpfxd651_01i.do")

# 활용할 요소 찾기

In [20]:
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

wait = WebDriverWait(driver, 10)
tbody = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#searchContentDiv > div.printdiv > table > tbody"))).text

In [21]:
tbody

'미국 USD 1,509.86 1.75 1,457.94 1.75 1,498.40 1,469.40 1,466.88 1,483.90 6.14181 1.0000\n일본 JPY (100) 1,038.70 1.75 1,002.98 1.75 1,030.84 1,010.84 1,010.19 1,020.84 2.59591 0.6879\n유로 EUR 1,672.56 1.99 1,607.30 1.99 1,656.32 1,623.54 1,621.58 1,639.93 4.32200 1.1051\n중국 CNY 211.08 5.00 190.98 5.00 203.04 199.02 0.00 201.03 4.34379 0.1355\n홍콩 HKD 195.02 1.97 187.50 1.97 193.17 189.35 189.08 191.26 5.73500 0.1289\n태국 THB 44.80 5.00 40.11 6.00 43.09 42.25 42.21 42.67 4.02533 0.0288\n대만 TWD 50.72 13.10 40.37 10.00 0.00 0.00 0.00 44.85 3.58766 0.0302\n필리핀 PHP 28.41 10.00 23.72 8.20 26.08 25.58 0.00 25.83 7.37000 0.0174\n싱가포르 SGD 1,121.01 1.99 1,077.27 1.99 1,110.13 1,088.15 1,086.87 1,099.14 4.75433 0.7407\n호주 AUD 901.75 1.97 866.91 1.97 893.17 875.49 873.99 884.33 6.22966 0.5959\n베트남 VND (100) 6.38 11.80 5.04 11.80 5.76 5.66 0.00 5.71 6.60833 0.0038\n영국 GBP 1,941.80 1.97 1,866.78 1.97 1,923.33 1,885.25 1,881.85 1,904.29 6.53200 1.2833\n캐나다 CAD 1,062.51 1.97 1,021.47 1.97 1,052.40 1,031.58 1,030.21 1,041.99 4.75533 0.7022\n말레이시아 MYR 354.35 7.40 305.53 7.40 0.00 326.65 0.00 329.94 5.26066 0.2223\n러시아 RUB 18.82 9.50 14.19 17.50 17.79 16.59 0.00 17.19 2.97500 0.0116\n남아공화국 ZAR 80.93 8.00 68.95 8.00 75.83 74.05 0.00 74.94 9.60100 0.0505\n노르웨이 NOK 140.79 3.30 128.54 5.70 137.66 134.94 134.70 136.30 6.44233 0.0919\n뉴질랜드 NZD 836.68 1.97 804.36 1.97 828.72 812.32 811.05 820.52 5.69366 0.5529\n덴마크 DKK 226.87 3.30 207.12 5.70 221.82 217.44 217.16 219.63 4.60633 0.1480\n멕시코 MXN 78.27 10.50 63.41 10.50 71.54 70.14 0.00 70.84 11.68600 0.0477\n몽골 MNT 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.42 13.47500 0.0003\n바레인 BHD 4,187.76 6.40 3,621.01 8.00 3,975.22 3,896.52 3,888.03 3,935.87 7.77200 2.6524\n방글라데시 BDT 0.00 0.00 0.00 0.00 0.00 0.00 0.00 12.21 12.18010 0.0082\n브라질 BRL 271.85 10.20 222.03 10.00 0.00 243.73 0.00 246.69 14.51900 0.1662\n브루나이 BND 1,143.10 4.00 1,033.20 6.00 0.00 0.00 0.00 1,099.14 4.67500 0.7407\n사우디아라비아 SAR 420.17 6.30 368.00 6.90 399.22 391.32 390.50 395.27 7.47766 0.2664\n스리랑카 LKR 0.00 0.00 0.00 0.00 0.00 0.00 0.00 4.92 11.50000 0.0033\n스웨덴 SEK 154.10 3.30 140.68 5.70 150.67 147.69 147.51 149.18 4.40700 0.1005\n스위스 CHF 1,797.81 1.97 1,728.35 1.97 1,780.71 1,745.45 1,744.32 1,763.08 2.31100 1.1881\n아랍에미리트공화국 AED 426.22 5.50 376.13 6.90 408.04 399.96 399.40 404.00 5.07500 0.2723\n알제리 DZD 0.00 0.00 0.00 0.00 0.00 0.00 0.00 11.13 8.22500 0.0075\n오만 OMR 4,123.76 7.00 3,584.22 7.00 0.00 0.00 0.00 3,853.99 4.62500 2.5972\n요르단 JOD 2,279.22 8.90 1,925.52 8.00 0.00 0.00 0.00 2,092.95 8.73900 1.4104\n이스라엘 ILS 429.93 10.00 359.59 8.00 0.00 0.00 0.00 390.85 6.56500 0.2634\n이집트 EGP 0.00 0.00 0.00 0.00 0.00 0.00 0.00 28.94 8.22500 0.0195\n인도 INR 0.00 0.00 0.00 0.00 17.33 16.95 0.00 17.14 9.06233 0.0116\n인도네시아 IDR (100) 9.63 10.00 7.89 10.00 8.84 8.68 8.67 8.76 8.42166 0.0059\n체코 CZK 70.60 8.50 59.22 9.00 65.78 64.36 0.00 65.07 5.73500 0.0439\n칠레 CLP 1.62 10.00 1.34 10.00 0.00 0.00 0.00 1.48 6.17100 0.0010\n카자흐스탄 KZT 0.00 0.00 0.00 0.00 0.00 0.00 0.00 2.85 16.97500 0.0019\n카타르 QAR 0.00 0.00 0.00 0.00 0.00 0.00 0.00 407.08 3.35500 0.2743\n케냐 KES 0.00 0.00 0.00 0.00 0.00 0.00 0.00 11.45 9.77500 0.0077\n콜롬비아 COP 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.33 0.00000 0.0002\n쿠웨이트 KWD 5,138.52 6.50 4,438.92 8.00 4,873.15 4,776.67 4,770.43 4,824.91 4.65766 3.2515\n탄자니아 TZS 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.56 10.36666 0.0004\n튀르키예 TRY 0.00 0.00 0.00 0.00 39.46 38.62 0.00 39.04 50.17500 0.0263\n파키스탄 PKR 0.00 0.00 0.00 0.00 0.00 0.00 0.00 5.29 18.12166 0.0036\n폴란드 PLN 412.18 8.00 351.12 8.00 385.84 377.46 0.00 381.65 8.13266 0.2572\n헝가리 HUF 4.38 9.30 3.69 8.00 4.05 3.97 0.00 4.01 8.44066 0.0027\n네팔 NPR 0.00 0.00 0.00 0.00 0.00 0.00 0.00 10.71 0.00000 0.0072\n마카오 MOP 0.00 0.00 0.00 0.00 0.00 0.00 0.00 185.56 0.00000 0.1250\n캄보디아 KHR 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.37 0.00000 0.0002\n피지 FJD 0.00 0.00 0.00 0.00 0.00 0.00 0.00 633.33 0.00000 0.4268\n리비아 LYD 0.00 0.00 0.00 0.00 269.48 264.16 0.00 266.82 0.00000 0.1798\n루마니아 RON 0.00 0.00 0.00 0.00 333.10 325.86 0.00 329.48 7.75633 0.2220\n미얀마 MMK 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.71 0.00000 0.0005\n에티오피아 ETB 0.00 0.00 0.00 0.00 0.00 0.00 0.00 11.22 0.00000 0.0076\n우즈베키스탄 UZS 0.00 0.00 0.00 0.00 0.00 0.00 0.00 0.11 0.00000 0.0001'

# 날짜 입력하기

In [34]:
from datetime import datetime, timedelta

start_date=datetime(1995,1,3)
end_date=datetime(1995,1,5)
date_list=[]

current_date=start_date
while current_date<=end_date:
    date_list.append(current_date.strftime("%Y-%m%d"))
    current_date+=timedelta(days=1)

In [57]:
from time import sleep  # 요청 사이 잠깐 멈추기
import pandas as pd
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from io import StringIO

# search_date = driver.find_element(By.CSS_SELECTOR, "#tmpInqStrDt")
# search_box = driver.find_element(By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")  

all_data=[]

for dt in date_list:
    search_date.clear()
    search_date.send_keys(dt)
    search_box.send_keys(Keys.ENTER)
    sleep(3)
    
    # 환율정보전체
    data = wait.until(EC.presence_of_element_located((By.CSS_SELECTOR, "#searchContentDiv > div.printdiv > table > tbody"))).text
    lines = data.strip().split('\n')
    # 2. 각 줄을 띄어쓰기로 나눈 리스트로 만들기
    rows = [line.split() for line in lines]
    # 3. 데이터프레임으로 변환
    df = pd.DataFrame(rows)
    # 컬럼명 지정 (예시)
    df.columns = [
    '국가', '통화', '기준단위', '송금받을때', '송금받을때_스프레드', '송금보낼때', '송금보낼때_스프레드',
    '매매기준율', '현찰살때', '현찰팔때', '현찰스프레드', 'TC살때', '외화수표_스프레드', '매매기준율_USD'
    ][:df.shape[1]]  # 혹시 열 개수가 다르면 자동 조정

    # 보기 좋게 출력
    print(df)

           국가   통화      기준단위   송금받을때 송금받을때_스프레드   송금보낼때 송금보낼때_스프레드     매매기준율  \
0          미국  USD    800.53    1.50     776.87    1.50     791.80    785.60
1          일본  JPY     (100)  798.89       1.50  775.29       1.50    791.81
2          유로  EUR      0.00    0.00       0.00    0.00     975.40    959.92
3          중국  CNY      0.00    0.00       0.00    0.00      94.12      0.00
4          홍콩  HKD    103.45    3.00     100.41    3.00     102.74    101.12
5          태국  THB     32.53    3.00      30.65    3.00      31.84     31.34
6        싱가포르  SGD    549.06    3.00     532.84    3.00     545.27    536.63
7          호주  AUD    621.08    3.00     602.74    3.00     616.80    607.02
8          영국  GBP  1,248.38    3.00   1,211.50    3.00   1,239.77  1,220.11
9         캐나다  CAD    571.02    3.00     554.16    3.00     567.09    558.09
10      말레이시아  MYR    313.56    3.00     304.30    3.00     311.40    306.46
11       노르웨이  NOK    118.35    3.00     114.87    3.00     117.54    115.68
12       뉴질랜드  NZD    512.50    3.00     497.36    3.00     508.96    500.90
13        덴마크  DKK    131.58    3.00     127.70    3.00     130.67    128.61
14        바레인  BHD  2,123.42    3.00   2,060.66    3.00   2,108.77  2,075.31
15    사우디아라비아  SAR    213.42    3.00     207.12    3.00     211.95    208.59
16        스웨덴  SEK    107.69    3.00     104.51    3.00     106.94    105.26
17        스위스  CHF    607.40    3.00     589.46    3.00     603.21    593.65
18  아랍에미리트공화국  AED    217.96    3.00     211.52    3.00     216.45    213.03
19         인도  INR     25.89    3.00      24.39    3.00       0.00      0.00
20      인도네시아  IDR     (100)   36.97       3.00   34.83       3.00     36.18
21       쿠웨이트  KWD  2,663.99    3.00   2,585.27    3.00   2,645.62  2,603.64

      현찰살때      현찰팔때    현찰스프레드      TC살때 외화수표_스프레드
0     0.00    788.70   0.00000    1.0000      None
1   782.37      0.00    787.09   0.00000    0.9980
2   957.94    967.66   7.37000    1.2269      None
3     0.00     93.38   1.00000    0.1184      None
4     0.00    101.93   0.00000    0.1292      None
5    31.26     31.59  11.25000    0.0401      None
6     0.00    540.95   0.00000    0.6859      None
7     0.00    611.91   0.00000    0.7758      None
8     0.00  1,229.94   0.00000    1.5595      None
9     0.00    562.59   0.00000    0.7133      None
10    0.00    308.93   0.00000    0.3917      None
11    0.00    116.61   0.00000    0.1479      None
12    0.00    504.93   0.00000    0.6402      None
13    0.00    129.64   0.00000    0.1644      None
14    0.00  2,092.04   0.00000    2.6525      None
15    0.00    210.27   0.00000    0.2666      None
16    0.00    106.10   0.00000    0.1345      None
17    0.00    598.43   0.00000    0.7588      None
18    0.00    214.74   0.00000    0.2723      None
19    0.00     25.14   9.25000    0.0319      None
20   35.62     35.48     35.90  16.37000    0.0455
21    0.00  2,624.63   0.00000    3.3278      None
           국가   통화      기준단위   송금받을때 송금받을때_스프레드   송금보낼때 송금보낼때_스프레드     매매기준율  \
0          미국  USD    800.33    1.50     776.67    1.50     791.60    785.40
1          일본  JPY     (100)  794.76       1.50  771.28       1.50    787.71
2          유로  EUR      0.00    0.00       0.00    0.00     971.40    956.00
3          중국  CNY      0.00    0.00       0.00    0.00      94.11      0.00
4          홍콩  HKD    103.42    3.00     100.38    3.00     102.71    101.09
5          태국  THB     32.49    3.00      30.61    3.00      31.80     31.30
6        싱가포르  SGD    550.50    3.00     534.24    3.00     546.70    538.04
7          호주  AUD    614.92    3.00     596.76    3.00     610.68    601.00
8          영국  GBP  1,251.91    3.00   1,214.91    3.00   1,243.27  1,223.55
9         캐나다  CAD    569.36    3.00     552.54    3.00     565.43    556.47
10      말레이시아  MYR    313.91    3.00     304.65    3.00     311.75    306.81
11       노르웨이  NOK    117.82    3.00     114.34    3.00     117.00    115.16
12       뉴질랜드  NZD    511.92    3.00     496.80    3.00     508.39    500.33
13        덴마크  DKK    130.91    3.00     127.05    3.00     129.75    128.21
14        바레인  BHD  2,123.45    3.00   2,060.69    3.00   2,108.80  2,075.34
15    사우디아라비아  SAR    213.36    3.00     207.06    3.00     211.89    208.53
16        스웨덴  SEK    107.29    3.00     104.13    3.00     106.55    104.87
17        스위스  CHF    608.84    3.00     590.86    3.00     604.64    595.06
18  아랍에미리트공화국  AED    217.92    3.00     211.48    3.00     216.41    212.99
19         인도  INR     25.89    3.00      24.39    3.00       0.00      0.00
20      인도네시아  IDR     (100)   37.01       3.00   34.87       3.00     36.22
21       쿠웨이트  KWD  2,670.42    3.00   2,591.50    3.00   2,652.00  2,609.92

      현찰살때      현찰팔때    현찰스프레드      TC살때 외화수표_스프레드
0     0.00    788.50   0.00000    1.0000      None
1   778.33      0.00    783.02   0.00000    0.9931
2   954.03    963.70   7.37000    1.2222      None
3     0.00     93.37   1.00000    0.1184      None
4     0.00    101.90   0.00000    0.1292      None
5    31.22     31.55  11.25000    0.0400      None
6     0.00    542.37   0.00000    0.6879      None
7     0.00    605.84   0.00000    0.7683      None
8     0.00  1,233.41   0.00000    1.5642      None
9     0.00    560.95   0.00000    0.7114      None
10    0.00    309.28   0.00000    0.3922      None
11    0.00    116.08   0.00000    0.1472      None
12    0.00    504.36   0.00000    0.6396      None
13    0.00    128.98   0.00000    0.1636      None
14    0.00  2,092.07   0.00000    2.6532      None
15    0.00    210.21   0.00000    0.2666      None
16    0.00    105.71   0.00000    0.1341      None
17    0.00    599.85   0.00000    0.7607      None
18    0.00    214.70   0.00000    0.2723      None
19    0.00     25.14   9.25000    0.0319      None
20   35.66     35.52     35.94  16.37000    0.0456
21    0.00  2,630.96   0.00000    3.3367      None
           국가   통화      기준단위   송금받을때 송금받을때_스프레드   송금보낼때 송금보낼때_스프레드     매매기준율  \
0          미국  USD    801.14    1.50     777.46    1.50     792.40    786.20
1          일본  JPY     (100)  790.74       1.50  767.38       1.50    783.73
2          유로  EUR      0.00    0.00       0.00    0.00     971.92    956.50
3          중국  CNY      0.00    0.00       0.00    0.00      94.21      0.00
4          홍콩  HKD    103.48    3.00     100.44    3.00     102.77    101.15
5          태국  THB     32.51    3.00      30.63    3.00      31.82     31.32
6        싱가포르  SGD    550.99    3.00     534.71    3.00     547.19    538.51
7          호주  AUD    616.03    3.00     597.83    3.00     611.78    602.08
8          영국  GBP  1,250.17    3.00   1,213.23    3.00   1,241.55  1,221.85
9         캐나다  CAD    571.44    3.00     554.56    3.00     567.50    558.50
10      말레이시아  MYR    313.86    3.00     304.60    3.00     311.70    306.76
11       노르웨이  NOK    117.82    3.00     114.34    3.00     117.00    115.16
12       뉴질랜드  NZD    511.01    3.00     495.91    3.00     507.48    499.44
13        덴마크  DKK    130.78    3.00     126.92    3.00     129.88    127.82
14        바레인  BHD  2,125.60    3.00   2,062.78    3.00   2,110.94  2,077.44
15    사우디아라비아  SAR    213.55    3.00     207.25    3.00     212.08    208.72
16        스웨덴  SEK    107.37    3.00     104.21    3.00     106.63    104.95
17        스위스  CHF    610.39    3.00     592.35    3.00     606.18    596.56
18  아랍에미리트공화국  AED    218.14    3.00     211.70    3.00     216.63    213.21
19         인도  INR     25.91    3.00      24.41    3.00       0.00      0.00
20      인도네시아  IDR     (100)   37.00       3.00   34.86       3.00     36.21
21       쿠웨이트  KWD  2,670.91    3.00   2,591.97    3.00   2,652.49  2,610.39

      현찰살때      현찰팔때    현찰스프레드      TC살때 외화수표_스프레드
0     0.00    789.30   0.00000    1.0000      None
1   774.39      0.00    779.06   0.00000    0.9870
2   954.53    964.21   7.37000    1.2216      None
3     0.00     93.47   1.00000    0.1184      None
4     0.00    101.96   0.00000    0.1292      None
5    31.24     31.57  11.25000    0.0400      None
6     0.00    542.85   0.00000    0.6878      None
7     0.00    606.93   0.00000    0.7689      None
8     0.00  1,231.70   0.00000    1.5605      None
9     0.00    563.00   0.00000    0.7133      None
10    0.00    309.23   0.00000    0.3918      None
11    0.00    116.08   0.00000    0.1471      None
12    0.00    503.46   0.00000    0.6379      None
13    0.00    128.85   0.00000    0.1632      None
14    0.00  2,094.19   0.00000    2.6532      None
15    0.00    210.40   0.00000    0.2666      None
16    0.00    105.79   0.00000    0.1340      None
17    0.00    601.37   0.00000    0.7619      None
18    0.00    214.92   0.00000    0.2723      None
19    0.00     25.16   9.25000    0.0319      None
20   35.65     35.51     35.93  16.37000    0.0455
21    0.00  2,631.44   0.00000    3.3339      None

In [49]:
# 누적된 전체 데이터프레임 생성
final_df = pd.concat(all_data, ignore_index=True)

# 저장 예시
# final_df.to_csv("exchange_rates.csv", index=False, encoding='utf-8-sig')

TypeError: cannot concatenate object of type '<class 'list'>'; only Series and DataFrame objs are valid

In [46]:
final_df

      0                                                  1        기준일
0  통화선택  선택하세요 USD:달러(미국) EUR:유로(유럽연합) JPY:100엔(일본) CNY...  1995-0103
1  일자선택              연월일 8자리로 ‘-’ 없이 입력해야 합니다. 예) 20160101  1995-0103
2  고시회차                                 최초  최종  특정회차  고시회차  1995-0103
3  통화선택  선택하세요 USD:달러(미국) EUR:유로(유럽연합) JPY:100엔(일본) CNY...  1995-0104
4  일자선택              연월일 8자리로 ‘-’ 없이 입력해야 합니다. 예) 20160101  1995-0104
5  고시회차                                 최초  최종  특정회차  고시회차  1995-0104
6  통화선택  선택하세요 USD:달러(미국) EUR:유로(유럽연합) JPY:100엔(일본) CNY...  1995-0105
7  일자선택              연월일 8자리로 ‘-’ 없이 입력해야 합니다. 예) 20160101  1995-0105
8  고시회차                                 최초  최종  특정회차  고시회차  1995-0105

In [62]:
from time import sleep  # 요청 사이 잠깐 멈추기
import pandas as pd
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from io import StringIO

# search_date = driver.find_element(By.CSS_SELECTOR, "#tmpInqStrDt")
# search_box = driver.find_element(By.CSS_SELECTOR, "#HANA_CONTENTS_DIV > div.btnBoxCenter > a")  

all_data=[]

for dt in date_list:
    search_date.clear()
    search_date.send_keys(dt)
    search_box.send_keys(Keys.ENTER)
    sleep(3)
    
    table_html = driver.find_element(By.CSS_SELECTOR, "#searchContentDiv > div.printdiv > table").get_attribute("outerHTML")

    # 문자열로 넘기기 위해 StringIO 사용
    df = pd.read_html(StringIO(table_html))[0]
    df['조회일'] = dt
    all_data.append(df)

# 모든 데이터를 하나의 DataFrame으로 병합
result_df = pd.concat(all_data, ignore_index=True)
result_df

                 통화       현찰                              송금           \
                 통화     사실 때            파실 때            보낼 때     받을 때
                 통화       환율 Spread       환율 Spread     보낼 때     받을 때
0            미국 USD   800.53    1.5   776.87    1.5   791.80   785.60
1      일본 JPY (100)   798.89    1.5   775.29    1.5   791.81   782.37
2            유로 EUR     0.00    0.0     0.00    0.0   975.40   959.92
3            중국 CNY     0.00    0.0     0.00    0.0    94.12     0.00
4            홍콩 HKD   103.45    3.0   100.41    3.0   102.74   101.12
..              ...      ...    ...      ...    ...      ...      ...
61          스위스 CHF   610.39    3.0   592.35    3.0   606.18   596.56
62    아랍에미리트공화국 AED   218.14    3.0   211.70    3.0   216.63   213.21
63           인도 INR    25.91    3.0    24.41    3.0     0.00     0.00
64  인도네시아 IDR (100)    37.00    3.0    34.86    3.0    36.21    35.65
65         쿠웨이트 KWD  2670.91    3.0  2591.97    3.0  2652.49  2610.39

   외화 수표 파실때   매매 기준율  환가 료율  미화 환산율        조회일
   외화 수표 파실때   매매 기준율  환가 료율  미화 환산율
   외화 수표 파실때   매매 기준율  환가 료율  미화 환산율
0       0.00   788.70   0.00  1.0000  1995-0103
1       0.00   787.09   0.00  0.9980  1995-0103
2     957.94   967.66   7.37  1.2269  1995-0103
3       0.00    93.38   1.00  0.1184  1995-0103
4       0.00   101.93   0.00  0.1292  1995-0103
..       ...      ...    ...     ...        ...
61      0.00   601.37   0.00  0.7619  1995-0105
62      0.00   214.92   0.00  0.2723  1995-0105
63      0.00    25.16   9.25  0.0319  1995-0105
64     35.51    35.93  16.37  0.0455  1995-0105
65      0.00  2631.44   0.00  3.3339  1995-0105

[66 rows x 12 columns]

In [ ]:
result