# 데이터 1개 수집 테스트

In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from datetime import datetime, timedelta
import pandas as pd
import time

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")


driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )

url = "https://play.google.com/store/apps/details?id=viva.republica.toss"
driver.get(url)

In [2]:
driver.execute_script(f"window.scrollTo({0}, {1400})")
time.sleep(2)

In [3]:
# 평점 및 리뷰 옆의 -> 버튼 클릭
wait = WebDriverWait(driver, 10)
button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[aria-label*='평점 및 리뷰 자세히 알아보기']")))
button.click()

In [4]:
# 리뷰 더 보기 링크 클릭
wait = WebDriverWait(driver, 10)
button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#ow14 > section > div > div.Jwxk6d > div:nth-child(5) > div > div > button")))
button.click()

TimeoutException: Message:

In [ ]:
sortBy_1

In [5]:
# 최신순으로 리뷰를 정렬하기 위해서 버튼 클릭
wait = WebDriverWait(driver, 10)
button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#sortBy_1")))
button.click()

In [6]:
# 최신을 찾아 클릭
wait = WebDriverWait(driver, 10)
button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "span[aria-label*='최신']")))
button.click()

In [7]:
# 리뷰가 담긴 창을 찾아서 JavaScript로 1000px씩 아래로 스크롤
driver.execute_script("document.querySelector('.fysCi.Vk3ZVd').scrollBy(0, 1000)")

In [8]:
# 별점
driver.find_element(By.CSS_SELECTOR, "div.Jx4nYe > div").get_attribute("aria-label").split()[3][0]

'1'

In [32]:
# 리뷰일
review_date = driver.find_element(By.CSS_SELECTOR, "div.Jx4nYe > span.bp9Aid").text.replace("년 ", "-").replace("월 ", "-").replace("일", "")
review_date = datetime.strptime(review_date, "%Y-%m-%d")

In [33]:
review_date

datetime.datetime(2025, 4, 11, 0, 0)

In [34]:
# 오늘 날짜를 추출하고 2년 전 날짜를 계산해 반복문 조건으로 활용
today = datetime.today()
two_yr_ago = today - timedelta(days=365*2)
review_date < two_yr_ago

False

In [ ]:
# 사용자리뷰
user_review = driver.find_element(By.CSS_SELECTOR, "div.h3YV2d").text

In [14]:
# 회사 답변
reply = driver.find_element(By.CSS_SELECTOR, "div.ocpBU div.ras4vb > div").text #.get_attribute("innerHTML")

'안녕하세요. 수징 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주셔서 감사합니다. 반영될 수 있다 확답 드리기는 어려우나, 고객님께서 말씀해주신 내용은 팀내에 공유하여 보다 편리한 토스 사용 경험을 하실 수 있도록 노력 하겠습니다. 다른 문의 사항이 있다면 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.'

# 코드 합치기

In [53]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager
from datetime import datetime, timedelta
import pandas as pd
import time
from tqdm import tqdm

options = Options()
options.add_experimental_option("detach", True)
options.add_argument("start-maximized")
options.add_argument("Chrome/135.0.0.0")
options.add_argument("lang=ko_KR")
# 웹브라우저가 백그라운드에서 작동하도록 설정
options.add_argument("--headless")
options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
    )

url = "https://play.google.com/store/apps/details?id=viva.republica.toss"
driver.get(url)

# 평점 및 리뷰 옆의 -> 버튼 클릭
wait = WebDriverWait(driver, 10)
button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "button[aria-label*='평점 및 리뷰 자세히 알아보기']")))
button.click()

# 최신순으로 리뷰를 정렬하기 위해서 버튼 클릭
wait = WebDriverWait(driver, 10)
button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "#sortBy_1")))
button.click()

# 최신을 찾아 클릭
wait = WebDriverWait(driver, 10)
button = wait.until(EC.element_to_be_clickable((By.CSS_SELECTOR, "span[aria-label*='최신']")))
button.click()

time.sleep(5)

# 오늘 날짜를 추출하고 2년 전 날짜를 계산해 반복문 조건으로 활용
today = datetime.today()
two_yr_ago = today - timedelta(days=60)

all_reviews = ""
while True:
    try:
        # 리뷰가 담긴 창을 찾아서 JavaScript로 1000px씩 아래로 스크롤
        driver.execute_script("document.querySelector('.fysCi.Vk3ZVd').scrollBy(0, 1000)")
        time.sleep(1)

        # 리뷰일
        review_date = driver.find_elements(By.CSS_SELECTOR, "div.Jx4nYe > span.bp9Aid")[-1].text.replace("년 ", "-").replace("월 ", "-").replace("일", "")
        review_date = datetime.strptime(review_date, "%Y-%m-%d")
        all_reviews = driver.find_elements(By.CSS_SELECTOR, ".RHo1pe")
        print(review_date, len(driver.find_elements(By.CSS_SELECTOR, ".RHo1pe")), end="\r")
    except:
        print(review_date, len(driver.find_elements(By.CSS_SELECTOR, ".RHo1pe")), end="\r")
        all_reviews = driver.find_elements(By.CSS_SELECTOR, ".RHo1pe")
        
    if review_date < two_yr_ago:
        break

########################################################################
# 리뷰 데이터 추출

all_reviews = driver.find_elements(By.CSS_SELECTOR, ".RHo1pe")
result = []
for review in tqdm(all_reviews):
    review_date = review.find_elements(By.CSS_SELECTOR, "div.Jx4nYe > span.bp9Aid")[-1].text.replace("년 ", "-").replace("월 ", "-").replace("일", "")
    review_date = datetime.strptime(review_date, "%Y-%m-%d")
    # 별점
    rating = review.find_element(By.CSS_SELECTOR, "div.Jx4nYe > div").get_attribute("aria-label").split()[3][0]
    # 사용자리뷰
    user_review = review.find_element(By.CSS_SELECTOR, "div.h3YV2d").text
    # 회사 답변
    try:
        reply = review.find_element(By.CSS_SELECTOR, "div.ocpBU div.ras4vb > div").text #.get_attribute("innerHTML")
    except:
        reply = None
#     print(review_date, rating, user_review, reply)
    result.append((review_date, rating, user_review, reply))

result_df = pd.DataFrame(result, columns=["리뷰일", "평점", "사용자리뷰", "개발자답변"])    
result_df

 67%|████████████████████████████████████████████████████████                            | 2/3 [00:00<00:00, 16.95it/s]

2025-04-12 00:00:00 4 토스의 장점이 사용하기 편하다는 거였는데 업데이트되면서 갑자기 홈화면이 자동으로 간결하게 보기로 바뀌어서 너무너무 불편해요. 보이는 계좌도 앱이 알아서 설정해놓고 강제적으로 이 상태로 쓰게 됐고요. 누굴 위한 업데이트인지 모르겠습니다. 빠른 시일 내에 원래대로 돌아갔으면 좋겠네요. 안녕하세요. 은정 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주셔서 감사합니다. 반영될 수 있다 확답 드리기는 어려우나, 고객님께서 말씀해주신 내용은 팀내에 공유하여 보다 편리한 토스 사용 경험을 하실 수 있도록 노력 하겠습니다. 다른 문의 사항이 있다면 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905로 문의 부탁드립니다. 감사합니다.
2025-04-12 00:00:00 1 상담원 연결 보호 조치를 해제해주세요ㅠㅠ 안녕하세요. 윤수빈님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 점 양해 말씀 드립니다. 보다 자세한 확인 및 안내를 위해 24시간 운영되는 고객센터 1599-4905 로 편하실 때 문의 부탁 드려도 될까요? 일부 안내의 경우 리뷰를 통한 즉각적인 안내가 어려울 수 있는 점 양해 부탁 드립니다. 감사합니다.

100%|████████████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 17.98it/s]

2025-04-12 00:00:00 4 잔액가리기가 적용이 안됩니다! 금액가리기가 안된다구요. 개발자면은 항목은 알고 있어야하는거 아닌가요? 시스템 확인 부탁 드려요! 그리고 증권을 분리좀 해주세요! 안녕하세요. 박남규님, 토스팀입니다. 홈 화면 잔액 숨기기의 경우 아래 경로로 진행 및 시도 부탁드립니다. 1. 토스 앱 - 홈 - 자산 꾹 누르셔서 화면에서 금액 숨기기 2. 자산 탭으로 들어가신 후 해당 계좌 꾹 누르시어 화면에서 금액 숨기기 3. 자산 탭에서 우측 상단 편집 - 홈 화면에서 금액 숨기기 4. 토스 앱 - 홈 - 아래쪽 설정에서 금액 숨기기 만약, 위 경로로 진행이 안되신다면 보다 정확한 상담을 위해 24시간 운영되는 카카오톡(@toss) 또는 고객센터 1599-4905 로 편하실 때 언제든지 문의 부탁 드립니다. 감사합니다.

,리뷰일,평점,사용자리뷰,개발자답변
0,2025-04-12,4,토스의 장점이 사용하기 편하다는 거였는데 업데이트되면서 갑자기 홈화면이 자동으로 간...,"안녕하세요. 은정 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주셔..."
1,2025-04-12,1,상담원 연결 보호 조치를 해제해주세요ㅠㅠ,"안녕하세요. 윤수빈님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 점..."
2,2025-04-12,4,잔액가리기가 적용이 안됩니다! 금액가리기가 안된다구요. 개발자면은 항목은 알고 있어...,"안녕하세요. 박남규님, 토스팀입니다. 홈 화면 잔액 숨기기의 경우 아래 경로로 진행..."

In [55]:
all_reviews = driver.find_elements(By.CSS_SELECTOR, ".RHo1pe")
result = []
for review in tqdm(all_reviews):
    review_date = review.find_elements(By.CSS_SELECTOR, "div.Jx4nYe > span.bp9Aid")[-1].text.replace("년 ", "-").replace("월 ", "-").replace("일", "")
    review_date = datetime.strptime(review_date, "%Y-%m-%d")
    # 별점
    rating = review.find_element(By.CSS_SELECTOR, "div.Jx4nYe > div").get_attribute("aria-label").split()[3][0]
    # 사용자리뷰
    user_review = review.find_element(By.CSS_SELECTOR, "div.h3YV2d").text
    # 회사 답변
    try:
        reply = review.find_element(By.CSS_SELECTOR, "div.ocpBU div.ras4vb > div").text #.get_attribute("innerHTML")
    except:
        reply = None
#     print(review_date, rating, user_review, reply)
    result.append((review_date, rating, user_review, reply))

result_df = pd.DataFrame(result, columns=["리뷰일", "평점", "사용자리뷰", "개발자답변"])    
result_df

100%|████████████████████████████████████████████████████████████████████████████████| 860/860 [00:42<00:00, 20.42it/s]

,리뷰일,평점,사용자리뷰,개발자답변
0,2025-04-12,4,토스의 장점이 사용하기 편하다는 거였는데 업데이트되면서 갑자기 홈화면이 자동으로 간...,"안녕하세요. 은정 님, 토스팀입니다. 토스를 이용하시면서 느끼신 소중한 의견을 주셔..."
1,2025-04-12,1,상담원 연결 보호 조치를 해제해주세요ㅠㅠ,"안녕하세요. 윤수빈님, 토스팀입니다. 남겨주신 내용만으로는 정확한 확인이 어려운 점..."
2,2025-04-12,4,잔액가리기가 적용이 안됩니다! 금액가리기가 안된다구요. 개발자면은 항목은 알고 있어...,"안녕하세요. 박남규님, 토스팀입니다. 홈 화면 잔액 숨기기의 경우 아래 경로로 진행..."
3,2025-04-12,2,토스 목록에 할 일이 있다고 적혀있는데 눌러보면 할 일이 없다 뜨거든요? 그래서 진...,None
4,2025-04-12,5,좋아요.,None
...,...,...,...,...
855,2025-02-14,1,1일 댓글 정지 당했는데 아직도 안풀렸습니다.,"안녕하세요. 야신월 님, 토스팀입니다. 서비스 이용에 불편을 드린것 같아 마음이 무..."
856,2025-02-13,1,정신병자 전용 앱,"안녕하세요.Egg hello 님, 토스팀입니다. 서비스 이용에 불편을 드린것 같아 ..."
857,2025-02-13,1,어차피 포인트 쌓을 사람들은 1원이건 10원이건 주기만하면 감지덕지하고 누르니까 말...,"안녕하세요. KB Good 님, 토스팀입니다. 만족스러운 서비스를 제공하기 위해 노..."
858,2025-02-13,5,증시 캘린더 너무좋아요. 캘린더 위젯도 나왔으면 좋겠어요. 홈화면에 띄워놓고 수시로...,None
859,2025-02-13,5,진짜로 다 좋은데 타은행 잔액 반영이 너무 느려요 😢,"안녕하세요. 와우 님, 토스팀입니다. 우선 서비스 이용에 불편을 드린 것 같아 죄송..."